apiVersion: v1
stringData:
  DB_USER : "postgres"
  DB_PASSWORD: "misw-g23-db-pwd"
  DB_HOST: "192.168.0.9"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  SECRET_TOKEN: "qwerty"
kind: Secret
metadata:
  name: appsecrets
