swagger: '2.0'
info:
  title: ABCall Management API
  description: API para gestionar incidentes y usuarios con backend en Cloud Run
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

# Definición de seguridad para API Key
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "Bearer token for accessing the API."

paths:
  /incidents:
    options:
      summary: CORS support Incidents
      operationId: corsSupportIncidents
      description: Enable CORS by returning correct headers
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '204':
          description: "Allow"
        '400':
          description: "Cors not allowed"
    get:
      summary: Listar todos los incidentes
      operationId: listIncidents
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: Lista de incidentes
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                description:
                  type: string
    post:
      summary: Crear un nuevo incidente
      operationId: createIncident
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: body
          name: incident
          description: Objeto de incidente que se va a crear
          schema:
            type: object
            properties:
              description:
                type: string
      responses:
        '201':
          description: Incidente creado
          schema:
            type: object
            properties:
              id:
                type: integer
              description:
                type: string

  /incidents/{id}:
    get:
      summary: Obtener un incidente específico por ID
      operationId: getIncident
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: ID del incidente a obtener
      responses:
        '200':
          description: Detalles del incidente
          schema:
            type: object
            properties:
              id:
                type: integer
              description:
                type: string
        '404':
          description: Incidente no encontrado
    put:
      summary: Actualizar un incidente específico por ID
      operationId: updateIncident
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: ID del incidente a actualizar
        - in: body
          name: incident
          description: Objeto de incidente que se va a actualizar
          schema:
            type: object
            properties:
              description:
                type: string
      responses:
        '200':
          description: Incidente actualizado
        '404':
          description: Incidente no encontrado
    delete:
      summary: Eliminar un incidente específico por ID
      operationId: deleteIncident
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: ID del incidente a eliminar
      responses:
        '204':
          description: Incidente eliminado
        '404':
          description: Incidente no encontrado

  /users/ping:
    get:
      summary: Ping the user service
      operationId: pingService
      # No requiere autenticación
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users/ping
      responses:
        '200':
          description: "Service is up"
          schema:
            type: object
            properties:
              message:
                type: string

  /users:
    options:
      summary: CORS support User POST
      operationId: corsSupportUsersPost
      description: Enable CORS by returning correct headers
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users
      responses:
        '204':
          description: "Allow"
        '400':
          description: "Cors not allowed"
    post:
      summary: Crear un nuevo usuario
      operationId: createUser
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users
      parameters:
        - in: body
          name: user
          description: Usuario que se va a crear
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
              role:
                type: string
      responses:
        '201':
          description: Usuario creado
          schema:
            type: object
            properties:
              id:
                type: string
              createdAt:
                type: string
              role:
                type: string

  /users/auth:
    post:
      summary: Autenticar usuario con credenciales
      operationId: loginToken
      # Este endpoint no requiere autenticación
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users/auth
      parameters:
        - in: body
          name: credentials
          description: Credenciales de usuario para autenticación
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Autenticación exitosa
          schema:
            type: object
            properties:
              id:
                type: string
              token:
                type: string
              expireAt:
                type: string
    options:
      summary: CORS support
      operationId: corsSupportAuth
      description: Enable CORS by returning correct headers
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users/auth
      responses:
        '204':
          description: "Allow"
        '400':
          description: "Cors not allowed"

  /users/me:
    options:
      summary: CORS support ME
      operationId: corsSupportMe
      description: Enable CORS by returning correct headers
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users/ping
      responses:
        '204':
          description: "Allow"
        '400':
          description: "Cors not allowed"
    get:
      summary: Obtener información del usuario autenticado
      operationId: getUserInfo
      security:
      - Bearer: []
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      parameters:
        - in: header
          name: Authorization
          required: true
          type: string
          description: Bearer token para autenticar la solicitud
      responses:
        '200':
          description: Información del usuario
          schema:
            type: object
            properties:
              id:
                type: string
              username:
                type: string
              email:
                type: string
              fullName:
                type: string
              dni:
                type: string
              phoneNumber:
                type: string
              status:
                type: string
              role:
                type: string

  /users/reset:
    post:
      summary: Restablecer todos los usuarios
      operationId: resetUsers
      x-google-backend:
        address: https://ms-users-719013485218.us-central1.run.app/users/reset
      responses:
        '200':
          description: Todos los datos de usuario fueron eliminados
          schema:
            type: object
            properties:
              msg:
                type: string

  /chat:
    options:
      summary: CORS support
      operationId: corsSupportChat
      description: Enable CORS by returning correct headers
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-chatbot-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '204':
          description: "Allow"
        '400':
          description: "Cors not allowed"
    post:
      summary: Interacción con el chatbot de ABCall
      operationId: chatbotService
      security:
      - Bearer: []
      x-google-backend:
        address: https://ms-chatbot-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      parameters:
        - in: body
          name: body
          required: true
          description: Datos para interactuar con el chatbot
          schema:
            type: object
            properties:
              message:
                type: string
                description: El mensaje del usuario al chatbot
                example: "crear incidencia"
              originType:
                type: string
                description: El origen del mensaje (por ejemplo, 'web', 'app')
                example: "web"
              userId:
                type: string
                description: ID del usuario que interactúa con el chatbot
                example: "12345"
      responses:
        '200':
          description: Respuesta proporcionada por el chatbot
          schema:
            type: object
            properties:
              message:
                type: string
                description: La respuesta del chatbot
              incidentId:
                type: string
                description: ID de la incidencia creada (si aplica)
              error:
                type: string
                description: Descripción del error (si ocurrió alguno)
        '401':
          description: Error de autenticación
          schema:
            type: object
            properties:
              message:
                type: string
                description: Descripción del error de autenticación
              error:
                type: string
                description: Detalles del error

  /plan:
    options:
      summary: CORS support Plan
      operationId: corsSupportPlan
      description: Enable CORS by returning correct headers
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '204':
          description: "Allow"
        '400':
          description: "Cors not allowed"
    get:
      summary: Crear plan
      operationId: createPlan
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: Crear plan
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                plan:
                  type: string
    put:
      summary: Actualizar un plan
      operationId: updatePlan
      security:
        - Bearer: []
      x-google-backend:
        address: https://ms-incidents-719013485218.us-central1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: plan
          in: body
          required: true
          description: Datos del plan a actualizar
          schema:
            type: object
            properties:
              id:
                type: integer
              plan:
                type: string
      responses:
        '200':
          description: Plan actualizado
          schema:
            type: object
            properties:
              message:
                type: string
              id:
                type: integer
              plan:
                type: string
              updateDate:
                type: string
                format: date-time
        '404':
          description: Plan no encontrado
