name: Android Unit Tests

on:
  push:
    paths:
      - 'mobile/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'mobile/**'
  workflow_dispatch: # Permitir ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [33]
        target: [default]
        arch: [x86_64]

    defaults:
      run:
        working-directory: mobile # Cambiar directorio de trabajo a 'mobile'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: "latest"
        accept-android-sdk-licenses: true
        packages: |
          platforms;android-${{ matrix.api-level }}
          build-tools;33.0.0

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest jacocoTestReport

    - name: Verify Coverage
      if: success()
      run: |
        # Calcula la cobertura de los ViewModels a partir del archivo XML de JaCoCo
        COVERAGE=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@covered)" build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
        MISSED=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@missed)" build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
        TOTAL=$((COVERAGE + MISSED))
        PERCENT=$((COVERAGE * 100 / TOTAL))
        echo "Line Coverage for ViewModels: $PERCENT%"
        if [ $PERCENT -lt 70 ]; then
          echo "Coverage for ViewModels is below 70%"
          exit 1
        fi
      continue-on-error: false

    - name: Archive test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/testDebugUnitTest
