name: Pruebas e integración de ramas de funcionalidad - BackEnd

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - opened
      - synchronize
      - review_requested
      - closed
    paths:
      - 'backend/**'  # Incluir todo backend
      - '!backend/infrastructure/**'  # Excluir infraestructura
      - '!backend/collections/**'     # Excluir collections

jobs:
  merge_develop:
    name: Mezclar develop a la rama feature
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Mezcla develop -> ${{ github.head_ref }}
      uses: tukasz/direct-merge-action@master
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         source-branch: develop
         target-branch: ${{ github.head_ref }}
         commit-message: "Se realiza merge de develop a la rama ${{ github.head_ref }}"
    
  run_tests:
    name: Ejecutar pruebas unitarias y cobertura
    permissions: write-all
    runs-on: ubuntu-latest
    needs: merge_develop
    strategy:
      matrix:
        os: [ubuntu-latest]
        service: [ms-incidents, ms-users, ms-chatbot]

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Cache de dependencias de Python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/${{ matrix.service }}/requirements.txt
        pip install pytest pytest-cov

    - name: Correr pruebas unitarias y cobertura con pytest en ${{ matrix.service }}
      run: |
        cd backend/${{ matrix.service }}
        pytest --cov=src --cov-fail-under=70 --cov-report=html
