name: Ejecución de pruebas unitarias en frontend Angular

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Proyecto a probar'
        required: true
        default: 'frontend/abcall-web'
        type: choice
        options:
          - frontend/abcall-web
jobs:         
  unit_tests:
    name: Pruebas unitarias en ${{ github.event.inputs.service }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configuración de Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias de frontend
      run: |
        cd frontend/abcall-web
        npm ci

    - name: Correr pruebas unitarias y verificar cobertura en ${{ github.event.inputs.service }}
      run: |
        cd frontend/abcall-web
        npm run test -- --code-coverage --watch=false
        if [ $(jq '.total.lines.pct' coverage/coverage-summary.json) -lt 70 ]; then exit 1; fi

    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: frontend/abcall-web/coverage
