name: Pruebas e integración de ramas de funcionalidad

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  merge_develop:
    name: Mezclar develop a la rama feature
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Mezcla develop -> ${{ github.head_ref }}
      uses: tukasz/direct-merge-action@master
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         source-branch: develop
         target-branch: ${{ github.head_ref }}
         commit-message: "Se realiza merge de develop a la rama ${{ github.head_ref }}"
    
  ms_incidents_tests:
    name: Pruebas unitarias y cobertura en ms-incidents
    permissions: write-all
    runs-on: ubuntu-latest
    needs: merge_develop
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Cache de dependencias de Python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/ms-incidents/requirements.txt

    - name: Correr pruebas unitarias en ms-incidents
      run: |
        cd backend/ms-incidents
        python -m unittest discover -s tests

    - name: Correr cobertura de código en ms-incidents
      run: |
        cd backend/ms-incidents
        coverage run -m unittest discover -s tests
        coverage report -m
        coverage xml

    - name: Verificación de cobertura
      run: |
        cd backend/ms-incidents
        coverage report -m --fail-under=70

  ms_users_tests:
    name: Pruebas unitarias y cobertura en ms-users
    permissions: write-all
    runs-on: ubuntu-latest
    needs: merge_develop
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Cache de dependencias de Python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/ms-users/requirements.txt

    - name: Correr pruebas unitarias en ms-users
      run: |
        cd backend/ms-users
        python -m unittest discover -s tests

    - name: Correr cobertura de código en ms-users
      run: |
        cd backend/ms-users
        coverage run -m unittest discover -s tests
        coverage report -m
        coverage xml

    - name: Verificación de cobertura
      run: |
        cd backend/ms-users
        coverage report -m --fail-under=70

  merge_to_develop:
    name: Mezclar la rama feature a develop
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    needs: [ms_incidents_tests, ms_users_tests]
    if: ${{ github.event.pull_request.merged == false && github.event.pull_request.approvals > 0 }}
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Mezcla ${{ github.head_ref }} -> develop
      uses: tukasz/direct-merge-action@master
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         source-branch: ${{ github.head_ref }}
         target-branch: develop
         commit-message: "Se realiza merge de la rama ${{ github.head_ref }} a develop"
