name: Manual - MB - Ejecución de pruebas unitarias
on:
  workflow_dispatch: # Permitir ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [33]
        target: [default]
        arch: [x86_64]

    defaults:
      run:
        working-directory: mobile # Cambiar directorio de trabajo a 'mobile'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest jacocoTestReport

    - name: Check if JaCoCo report exists
      if: success()
      run: |
        if [ ! -f app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml ]; then
          echo "JaCoCo report not found in mobile/app/build/reports/jacoco/testDebugUnitTest!"
          exit 1
        else
          echo "JaCoCo report found in mobile/app/build/reports/jacoco/testDebugUnitTest."
        fi
      continue-on-error: false

    - name: Verify Coverage
      if: success()
      run: |
        # Calcula la cobertura de los ViewModels a partir del archivo XML de JaCoCo
        COVERAGE=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@covered)" app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml)
        MISSED=$(xmllint --xpath "number(//report/package[@name='com/uniandes/abcall/viewmodel']/counter[@type='LINE']/@missed)" app/build/reports/jacoco/testDebugUnitTest/jacocoTestReport.xml)
        TOTAL=$((COVERAGE + MISSED))
        PERCENT=$((COVERAGE * 100 / TOTAL))
        echo "Line Coverage for ViewModels: $PERCENT%"
        if [ $PERCENT -lt 70 ]; then
          echo "Coverage for ViewModels is below 70%"
          exit 1
        fi
      continue-on-error: false

    - name: Archive test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/testDebugUnitTest
